Use arg lists instead of strings
ciromattia/kcc pull request #581
Opened 2023-08-17 17:10 UTC by axu2

This also means you don't get wrecked by `"` or `'` in the filename.

2023-10-26 19:14 UTC, darodi commented
@axu2 
Master branch

![image](https://github.com/ciromattia/kcc/assets/4682830/46e32b52-a46c-4732-aa21-f04c674c1d45)

your PR:

![image](https://github.com/ciromattia/kcc/assets/4682830/9015c5da-caaa-49de-8fd3-73c357bdc11a)

This doesn't seem to work

2023-10-26 19:19 UTC, darodi requested changes
not working, see 
https://github.com/ciromattia/kcc/pull/581#issuecomment-1781753498

2023-10-26 20:40 UTC, axu2 commented
Whoops, didn't notice since that error got bypassed on mac due to `unar`

I'll also improve the error logging.

![image](https://github.com/ciromattia/kcc/assets/20757319/658ef466-e8a4-483a-955f-286af9aedace)

2023-11-09 22:27 UTC, darodi approved these changes

2023-11-09 22:27 UTC, merged