fix #582 - comicrack xml list oob
ciromattia/kcc pull request #604
Opened 2023-10-07 14:44 UTC by Ger4ldK

The purpose of this PR is to fix the issues encountered in #582, from what I was able to find based on the OP's file and my own files when using the tool, it seems that the source files we have contain 2-in-1 spread pages, which affects how the index counts up when working with the Comicrack XML Pages/Bookmarks tag. I have added a checkbox under Manga mode(as it seems quite common in manga series to have 2-page spreads) to toggle this option and adjust the math in the loop when converting files. If this checkbox is checked, the delta is adjusted when the Spreat splitter is either Unchecked or Indeterminate (state 0 or 1), and in the case where 'Rotate' is chosen (state 2), the pageid is decremented by 1 each time it encounters a spread to move the bookmark to the correct location. In all 3 states, I did not encounter the error again and my bookmarks were also in the correct positions

I am not sure if this is something that everyone is going to be using, but I will make this PR as a reference for anyone who is encountering the issue faced in #582, I've also tried to maintain the previous behavior as best I can. I am quite new to open source work so feel free to provide any feedback!

2023-10-07 16:22 UTC, axu2 commented
I'm personally against making users need to check a box to avoid ComicRack related errors. Normal users shouldn't need to check if their source files are merged are not.

Is it possible to do something like:

```python
try:
    original_method()
except IndexError as e:
    your_method()
```

@vinhtq115 Can you confirm this doesn't cause a regression with #558? I deleted the source file.

2023-10-07 16:34 UTC, Ger4ldK commented
Yep, I also don't think its the best idea to have this extra checkbox, will try the except IndexError method while I'm converting some more of my library, thanks for the work you guys put into the project!

2023-10-07 16:43 UTC, axu2 commented
Please add the following text to the first post so GitHub tags it properly:

> Fixes #582 
> Fixes #586 

And change the title to "fix list index out of range for comicrack"

2023-10-08 03:41 UTC, Ger4ldK commented
updated the title and first post, but in terms of the fixing, i think i found that the IndexError isn't raised on some other books I was converting - these books didn't have a bookmark in the last few pages, which i think is what causes the calculation to go OOR. The error is no longer showing, but I'm getting inconsistent bookmarks again for books that do not have a bookmark near the final pages

2023-10-08 04:05 UTC, axu2 commented
Oh hmmm, so the error isn't guaranteed, that's good information.

Maybe go back to original implementation? Can you determine `options.alreadymerged` based on the filenames by looking for `kcc-a`?

2023-10-08 04:56 UTC, Ger4ldK commented
Yep, currently working and testing on determining the conditions for the different method by comparing the original file count against the resulting pages after pages are split - a 'true' page count, will update soon

2023-10-10 22:38 UTC, axu2 commented
Thank you for the cleanup, much easier to review. 

Am I missing something or does this code not preserve the previous behavior? I thought this was an issue related to large files joined by comic rack but these changes appear to apply to all files with comic rack bookmarks.

2023-10-11 00:27 UTC, vinhtq115 commented
> @vinhtq115 can you provide a test file as well? I want to make sure we don't break your use case. I unfortunately already deleted the one you provided in #558 I believe the file was a complete english official volume with spreads joined. The current code placed the bookmarks correctly for that file.

[Here](https://we.tl/t-yukzZBaF3w) is the test file.

2023-10-11 01:17 UTC, Ger4ldK commented
> Thank you for the cleanup, much easier to review.
> 
> Am I missing something or does this code not preserve the previous behavior? I thought this was an issue related to large files joined by comic rack but these changes appear to apply to all files with comic rack bookmarks. Unfortunately I have no comicrack files to test myself.

Oh, I might have misunderstood the splitcheck code then, but my assumption is that when a split is needed, that likely meant that a spread was joined in the source file, which is why i set the `options.hasspreadpages` flag to True. It's going to run on all CR files that detected a split, but if they don't, it should behave as it did previously. I could duplicate the code and maintain the old version too for easier readability. Let me know if I should do that.

2023-10-11 01:27 UTC, axu2 commented
@Ger4ldK Be aware that the provided test file is NSFW. Be careful when you open it.

2023-10-11 02:20 UTC, Ger4ldK commented
> @Ger4ldK Be aware that the provided test file is NSFW. Be careful when you open it, though please report how it interacts with your changes.

thanks for the heads up 😆 my own test files are NSFW too, so no worries, will report back with my results

2023-10-11 03:14 UTC, Ger4ldK commented
Tested with @vinhtq115's file, and it seems to be following the pages defined in comicinfo.xml, which means it's working, but the bookmarks defined by them are not the same as the ones in the ToC, which is what I did for my own files, so I'm not sure if this is working for them. Might have to redesign this a bit. I don't have ComicRack and just wrote the XML based on the example in the docs, which might make a huge difference in how this all behaves now

@vinhtq115 was the page numbers adjusted in the test file due to the issues in #558?

2023-10-11 03:16 UTC, vinhtq115 commented
> Tested with @vinhtq115's file, and it seems to be following the pages defined in comicinfo.xml, which means it's working, but the bookmarks defined by them are not the same as the ones in the ToC, which is what I did for my own files, so I'm not sure if this is working for them. Might have to redesign this a bit. I don't have ComicRack and just wrote the XML based on the example in the docs, which might make a huge difference in how this all behaves now
> 
> @vinhtq115 was the page numbers adjusted in the test file due to the issues in #558?

I bookmarked it as I had done in #558 (no differences).

2023-10-11 03:19 UTC, Ger4ldK commented
> > Tested with @vinhtq115's file, and it seems to be following the pages defined in comicinfo.xml, which means it's working, but the bookmarks defined by them are not the same as the ones in the ToC, which is what I did for my own files, so I'm not sure if this is working for them. Might have to redesign this a bit. I don't have ComicRack and just wrote the XML based on the example in the docs, which might make a huge difference in how this all behaves now
> > @vinhtq115 was the page numbers adjusted in the test file due to the issues in #558?
> 
> I bookmarked it as I had done in #558 (no differences).

hmm, might rework my design slightly then, will work with your test file since it helps me understand. Thanks for the info!

2023-10-11 18:10 UTC, Ger4ldK commented
Update, managed to get it working with the testing file, and it does not have issues with mine as well

Summarizing the fix as best I can here, this should fix the error of the index going OOR, and additionally it also fixed issues with bookmark drift that I encountered due to my manual editing of my ComicInfo.xml file. Based on my testing with both files and all 3 possible states, the bookmarks all appear correctly for me, I'm no longer encountering issues with the index going OOR when the bookmark is near the end, where `((pageid + global_diff) > len(filelist))` as well

2023-10-11 19:16 UTC, axu2 commented
@Ger4ldK Please confirm the results with the LARGE comicrack joined file from #582

2023-10-15 05:43 UTC, Ger4ldK commented
Sorry for the delay, tested with the file in #582 and it seems to be fine now, no index error. Will generate the binaries and let the OP of the issue test as well to confirm

2023-10-15 21:44 UTC, axu2 commented
You just link the individual runs.

2023-10-15 22:00 UTC, axu2 requested changes
Some small nitpicks.

2023-10-15 22:00 UTC, axu2 commented on kindlecomicconverter/comic2ebook.py
> +            if (options.splitter == 0 or options.splitter == 2):
`if options.splitter != 1`

2023-10-15 22:00 UTC, axu2 commented on kindlecomicconverter/comic2ebook.py
> +                    if'-kcc-b' in filelist[x][1]:
missing space before `'-kcc-b'`

2023-10-15 22:00 UTC, axu2 commented on kindlecomicconverter/comic2ebook.py
> +        for page in output[0]:
Is it possible to use this python feature somewhere instead of indexing?

```
item1, item2 = some_function_that_returns_tuple_of_two_items()
```

2023-10-17 11:46 UTC, Ger4ldK commented on kindlecomicconverter/comic2ebook.py
> +            if (options.splitter == 0 or options.splitter == 2):
updated to `if options.spreadadjust and options.splitter != 1:`

2023-10-17 11:47 UTC, Ger4ldK commented on kindlecomicconverter/comic2ebook.py
> +        for page in output[0]:
ooh, thanks for this, let me rewrite it

2023-10-17 13:05 UTC, Ger4ldK commented
> You just link the individual runs.
> 
> Make sure you tick Stretch/Upscale in the test file so it gets split after 400 mb. Replicate his exact settings to trigger 400 mb split.

was wondering why i wasn't getting a 400mb split even with the same settings, realized i had to select a Kindle device and got this now 
![image](https://github.com/ciromattia/kcc/assets/44670032/be38fb10-548f-4cc7-9482-79a6be268663)
Any idea what this is caused by? The line at 218 and the error message isn't giving me much info

2023-10-17 20:03 UTC, axu2 commented
The error is more easy to see if you revert your changes. 

I feel like there are multiple issues here. 

1) @vinhtq115 where did you get the bookmarks for your test file? Did you manually add? Your test file already worked prior to this PR. 

2) the large test file had bookmarks generated from comicrack directly from #582. I thought this pr fixed it. Fixing that test file is very important. 

3) @Ger4ldK you manually added bookmarks? This is tricky if you make them different than comicrack. 

Honestly we should probably just skip the bookmark related code if a 400 mb split is detected.

2023-10-17 22:21 UTC, vinhtq115 commented
> 1. @vinhtq115 where did you get the bookmarks for your test file? Did you manually add? Your test file already worked prior to this PR.

I manually created it using ComicTagger.

2023-10-19 15:21 UTC, axu2 commented on kindlecomicconverter/comic2ebook.py
>      # Overwrite chapternames if tree is flat and ComicInfo.xml has bookmarks
Maybe this entire code section should be skipped if a 400 mb split is detected?

2023-10-21 03:06 UTC, axu2 commented on kindlecomicconverter/comic2ebook.py
> +                pageid = filelen - 1
pageid = max(pageid, filelen -1)

2023-10-22 05:41 UTC, axu2 commented on kindlecomicconverter/comic2ebook.py
> +        filelen = len(filelist)
Just use `len(filelist)` per comment below.

2023-10-22 05:41 UTC, axu2 commented on kindlecomicconverter/comic2ebook.py
> +        return (output, spreadadjust)
no need for parentheses to return a tuple

2023-11-28 15:28 UTC, axu2 commented
Closed due to inactivity. Reopen as needed. May already be fixed by #620

2023-11-28 15:28 UTC, closed without merging