Replaced StrictVersion with packaging.version.parse for Python 3.12 compatibility
ciromattia/kcc pull request #727
Opened 2024-08-01 11:58 UTC by morpheby

Simple drop-in replacement for the `distutils.StrictVersion`. Should fix #618 and unblock #605.

2024-08-01 13:55 UTC, axu2 commented
Shouldn't we use version.Version and not version.parse?

Also, we need to remove distutils entirely, not just StrictVersion. Id check out the partial commit linked in the issue

2024-08-01 19:23 UTC, morpheby commented
@axu2 Good point. I wasn’t really paying attention and just fixed what I needed to start the KCC from python. I’ll check and fix everything else next time I have some free time :) (hopefully soon)

2024-08-01 19:26 UTC, morpheby commented
As for `Version` initializer vs `parse`, according to documentation both seem equivalent and a matter of style.

2024-08-01 23:23 UTC, axu2 commented
The rest of distutils is only used when calling `python setup.py build_binary`.

Also, I'd prefer using `Version`, `parse` literally just calls `Version`,

https://github.com/pypa/packaging/blob/main/src/packaging/version.py#L47

2024-08-21 14:37 UTC, axu2 requested changes
In `setup.py`, you need to remove 

```python
import distutils.cmd
class BuildBinaryCommand(distutils.cmd.Command):
```

with 

```python
class BuildBinaryCommand(setuptools.Command):
```

And verify that `python setup.py build_binary` works.

2024-08-21 14:37 UTC, axu2 commented on requirements.txt
> +packaging==24.1
Follow the `>=` pattern as the rest of the requirements.

2024-08-21 14:37 UTC, axu2 commented on kindlecomicconverter/shared.py
> +from packaging import version
ditto

2024-08-21 14:37 UTC, axu2 commented on kindlecomicconverter/KCC_gui.py
> +from packaging import version
I prefer 

```
from packaging.version import Version
```

Fun fact, parse literally just calls Version. But Version looks cleaner than version.parse

https://github.com/pypa/packaging/blob/main/src/packaging/version.py#L47

2024-08-21 14:37 UTC, axu2 commented on kindlecomicconverter/KCC_gui.py
> +            if ("b" not in __version__ and version.parse(latest_version) > version.parse(__version__)) \
That way it's just `Version(latest_version) > Version(_version_)`

2024-08-28 21:27 UTC, closed without merging